# Generated by Django 4.2.5 on 2024-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_itineraryitem_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='budget',
            field=models.CharField(choices=[(1000, '1000 - 2000'), (2000, '2000 - 3000'), (3000, '3000 - 4000'), (4000, '4000 - 5000')], max_length=100),
        ),
    ]
